<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>smyd_vint_navigation</name>
  <version>0.1.0</version>
  <description>ViNT ONNX 추론, topomap 경로 선택, waypoint 추종</description>
  <maintainer email="inhsroy@hanyang.ac.kr">InHyunseo</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>libopencv-dev</depend>
  <depend>onnxruntime_vendor</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
