vint_navigator_node:
  ros__parameters:
    radius: 2
    close_threshold: 3.0
    waypoint_index: 2
    goal_node: -1
    context_frames_per_second: 4.0
    inference_rate_hz: 2.0
    image_timeout_seconds: 2.0
    inference_threads: 2
    max_v: 0.2
    model_frame_rate: 4.0

waypoint_follower_node:
  ros__parameters:
    max_v: 0.2
    max_w: 0.4
    model_frame_rate: 4.0
    control_rate_hz: 10.0
    waypoint_timeout_seconds: 2.0
